primary_agent:
  llm: qwen/qwen3.8-27b
  llm_temperature: 0.0

swiss_airline_policy_rag:
  unstructured_docs: "data/unstructred_data/airline_policy"
  vectordb: "data/airline_policy_vectordb"
  collection_name: rag-chroma
  llm: qwen/qwen3.8-27b
  llm_temperature: 0.0
  embedding_model: text-embedding-3-small
  chunk_size: 500
  chunk_overlap: 100
  k: 2

stories_rag:
  unstructured_docs: "data/unstructred_data/stories"
  vectordb: "data/stories_vectordb"
  collection_name: stories-rag-chroma
  llm: qwen/qwen3.8-27b
  llm_temperature: 0.0
  embedding_model: text-embedding-3-small
  chunk_size: 500
  chunk_overlap: 100
  k: 2

travel_sqlagent_configs:
  travel_sqldb_dir: "data/travel.sqlite"
  llm: "qwen/qwen3.8-27b"
  llm_temperature: 0.0
  
chinook_sqlagent_configs:
  chinook_sqldb_dir: "data/Chinook.db"
  llm: "qwen/qwen3.8-27b"
  llm_temperature: 0.0

langsmith:
  tracing: "true"
  project_name: "rag_sqlagent_project"

tavily_search_api:
  tavily_search_max_results: 2

graph_configs:
  thread_id: 1 